name: Print Secret

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $((${{ secrets.COUNTER }} + 1)) | gh secret set COUNTER
      - run: echo "${{ secrets.COUNTER }}" | gh variable set TEST_COUNTER
      - name: Print Secret Value
        run: echo "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" | gh variable set TEST

