name: Print Secret

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Secret Value
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" | gh variable set TEST

