name: Print Secret

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $((${{ secrets.COUNTER }} + 1)) | gh secret set TEST
      - run: echo "${{ secrets.COUNTER }}" | gh variable set TEST
      - name: Print Secret Value
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" | gh variable set TEST

